services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: [8080]
    environment:
      TOKEN: ODE1MDk1MDA0MTQ0ODYxMjI0.Gx4e_X.LqdbsL-eMZTY7kZ0G8IJfq8POdEZl7HZcSpVJI
